name: Post Slack message

on:
  push:
    branches:
      - main
    paths:
      - 'data/scorecards/**'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1

    - name: Post Slack Message
      env:
         ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
         message="An updated file has been published to <https://github.com/cortexapps/learn-cortex|Learn Cortex>\n"
         message="${message}*Description*: ${{ github.event.head_commit.message }}\n"
         for file in ${ALL_CHANGED_FILES}; do
            message="${message}*File:* $file was changed\n"
         done
         curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" ${{ env.SLACK_WEBHOOK_URL }}
